### ISSUE TITLE
It doesn't seem to be working with Swift 2 new syntax

### ISSUE THREAD

**Issue by rogerluan** [watsonbox/ios_google_places_autocomplete#16]
Tried running the project on Xcode 7 and it asked me to convert the project to Swift 2 new syntax, although it wasn't successful doing so.

**Comment by briva** [comment]
Same issue.

**Comment by thekie** [comment]
+1

**Comment by piercifani** [comment]
You can check out this [PR](https://github.com/watsonbox/ios_google_places_autocomplete/pull/22)

**Comment by IbrahimYildirim** [comment]
+1
And @watsonbox its cool you have made this, but why didn't you organize it so it would be easier get an idea of whats going on and maybe made it more generic? Putting all code in one file is not good practise, seriously its like a labyrinth. 
@piercifani downloaded your changes, but gives me the error:
     `diff: /../Podfile.lock: No such file or directory
     diff: /Manifest.lock: No such file or directory
     error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.`

Tried everything to make it build, but just gave up.

**Comment by watsonbox** [comment]
I'll try to find some time at some point to have a look at this myself.  I haven't been able to upgrade due to working on an older project.

@IbrahimYildirim I put all the code in one file so it could be easily imported into projects targeting iOS 7.  See the [installation instructions](https://github.com/watsonbox/ios_google_places_autocomplete#installation) for more detail.  This is the same approach taken by [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON/blob/master/Source/SwiftyJSON.swift) and also [AlamoFire](https://github.com/Alamofire/Alamofire/blob/8e2e5251144a7792e8358e8ff9326bb7aa71ab7a/Source/Alamofire.swift) back when it supported iOS 7, to name but two.

**Comment by watsonbox** [comment]
Merged #25
